export const Colors = {
  BLACK100: '#1C1B1F',

  WHITE100: '#FFFFFF',

  GREY: '#D9D9D9',

  GREEN_BACKGROUND: '#E0EBED',
  GREEN_DARK: '#2D4D52',
  GREEN_DEEP: '#3DECAD',
  GREEN_SUB_TEXT: '#97AAAD',
}
